name: Build and Push JIRA Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [8.20.30,9.4.23,9.12.10,9.13.0,9.13.1,9.14.0,9.14.1,9.15.2,9.16.0,9.16.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: musanmaz/jira:${{ matrix.version }}
          build-args: |
            JIRA_VERSION=${{ matrix.version }}
            BUILD_DATE=${{ github.event.created_at }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ matrix.version }}
          release_name: JIRA version ${{ matrix.version }}
          body: Docker image for JIRA version ${{ matrix.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}